FROM docker.io/nvidia/cuda:12.8.0-devel-ubuntu24.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
       apt-get install -y \
        build-essential \
        ca-certificates \
        pkg-config \
        automake \
        autoconf \
        libtool \
        cmake \
        gdb \
        strace \
        wget \
        git \
        bzip2 \
        python3 \
        rdma-core \
        numactl \
        libconfig-dev \
        libuv1-dev \
        libfuse-dev \
        libfuse3-dev \
        libyaml-dev \
        libnl-3-dev \
        libnuma-dev \
        libsensors-dev \
        libcurl4-openssl-dev \
        libjson-c-dev \
        libibverbs-dev \
        --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ARG GDRCOPY_VER=2.4.4
RUN git clone --depth 1 --branch v${GDRCOPY_VER} https://github.com/NVIDIA/gdrcopy.git \
    && cd gdrcopy \
    && export CUDA_PATH=${CUDA_HOME:-$(echo $(which nvcc) | grep -o '.*cuda')} \
    && make CC=gcc CUDA=$CUDA_PATH lib \
    && make lib_install \
    && cd ../ && rm -rf gdrcopy

ARG cassini_headers_ref=9a8a738a879f007849fbc69be8e3487a4abf0952
RUN git clone https://github.com/HewlettPackard/shs-cassini-headers.git \
    && cd shs-cassini-headers \
    && git checkout ${cassini_headers_ref} \
    && cp -r include/* /usr/include/ \
    && cp -r share/* /usr/share/ \
    && cd .. \
    && rm -r shs-cassini-headers

ARG cxi_driver_ref=af5d2ed4114134ea4eaf095d16af619573729045
RUN git clone https://github.com/HewlettPackard/shs-cxi-driver.git \
    && cd shs-cxi-driver \
    && git checkout ${cxi_ddriver_ref} \
    && cp -r include/* /usr/include/ \
    && cd .. \
    && rm -r shs-cxi-driver

ARG libcxi_ref=3a33b3966d2898ab129458c8813b0cbcdcec06f5
RUN git clone https://github.com/HewlettPackard/shs-libcxi.git \
    && cd shs-libcxi \
    && git checkout ${libcxi_ref} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -r shs-libcxi

# Install libfabric
ARG libfabric_version=2.0.0
ARG libfabric_ref=c17230da527aada634e0cc50d9feafc83d7106ce
# Libfabric 2.0.0 seems to have a bug preventing compilation of the CXI provider, using main branch for now
RUN git clone --branch main --single-branch https://github.com/ofiwg/libfabric.git \
    && cd libfabric \
    && git checkout ${libfabric_ref} \
    && ./autogen.sh \
    && ./configure --prefix=/usr --with-cuda=/usr/local/cuda --enable-cuda-dlopen --enable-gdrcopy-dlopen --enable-cxi --enable-lnx --enable-efa \
    && make -j$(nproc) \
    && make install \
    && ldconfig \
    && cd .. \
    && rm -rf libfabric

# Install UCX
ARG UCX_VERSION=1.18.0
RUN wget https://github.com/openucx/ucx/releases/download/v${UCX_VERSION}/ucx-${UCX_VERSION}.tar.gz \
    && tar xzf ucx-${UCX_VERSION}.tar.gz \
    && cd ucx-${UCX_VERSION} \
    && mkdir build \
    && cd build \
    && ../configure --prefix=/usr --with-cuda=/usr/local/cuda --with-gdrcopy=/usr/local --enable-mt --enable-devel-headers \
    && make -j$(nproc) \
    && make install \
    && cd ../.. \
    && rm -rf ucx-${UCX_VERSION}.tar.gz ucx-${UCX_VERSION}
