site_name: cray-network-stack
nav:
  - Home: index.md
  #- 'User Guide':
  #  - 'Configuring Stacks': configuring.md
  #  - 'Building Stacks': building.md
theme:
  name: material
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    primary: deep orange
    accent: deep orange
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - tables
  - toc:
      permalink: true
repo_url: https://github.com/eth-cscs/cray-network-stack
