FROM quay.io/ethcscs/ompi:5.0.8-cxi-ofi2.1-cuda12.8

ARG nccl_tests_version=2.16.4
RUN wget -O nccl-tests-${nccl_tests_version}.tar.gz https://github.com/NVIDIA/nccl-tests/archive/refs/tags/v${nccl_tests_version}.tar.gz \
    && tar xf nccl-tests-${nccl_tests_version}.tar.gz \
    && cd nccl-tests-${nccl_tests_version} \
    && MPI=1 MPI_HOME=/opt/hpcx/ompi make -j$(nproc) \
    && cd .. \
    && rm -rf nccl-tests-${nccl_tests_version}.tar.gz

