image="/capstor/scratch/cscs/amadonna/quay.io+ethcscs+nv-hpc-benchmarks+25.04.01-cxi-ofi2.1-cuda12.8.sqsh"
entrypoint=false

[env]
PMIX_MCA_psec="native"
FI_PROVIDER="cxi"
FI_CXI_DISABLE_HOST_REGISTER="1"
NVSHMEM_REMOTE_TRANSPORT="libfabric"
NVSHMEM_LIBFABRIC_PROVIDER="cxi"
NVSHMEM_BOOTSTRAP="MPI"
NVSHMEM_BOOTSTRAP_PMI="PMIX"
NVSHMEM_DISABLE_CUDA_VMM="1"

[annotations]
com.hooks.cxi.enabled="false"
com.hooks.aws_ofi_nccl.enabled="1.14"
com.hooks.aws_ofi_nccl.variant="cuda12"

