image="/capstor/scratch/cscs/amadonna/quay.io+ethcscs+osu-mb+7.5-ompi5.0.8-cxi-ofi2.1-cuda12.8.sqsh"
entrypoint=false

[env]
PMIX_MCA_psec="native"

OMPI_MCA_btl="^tcp,ofi,vader,openib"
OMPI_MCA_pml="cm"
OMPI_MCA_mtl="ofi"
OMPI_MCA_opal_common_ofi_provider_include="cxi"
#FI_LOG_LEVEL="trace"
FI_HMEM_CUDA_USE_GDRCOPY="1"

[annotations]
com.hooks.cxi.enabled="false"
