internal-cxi:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.30
      gpu: cuda
  unify: true
  specs:
  - cray-mpich
  - cuda
  - gdb
  - libfabric@main fabrics=tcp,udp,cxi +uring
  - nccl
  - aws-ofi-nccl@master
  - cmake
  - ninja
  - osu-micro-benchmarks
  - nccl-tests
  #- xpmem
  - fftw
  - fmt
  - hdf5 +direct-vfd
  - gperftools
  - openblas threads=openmp
  - cudnn
  - cutensor
  - hydra
  - swig
  - libaio
  - faiss +python
  - python
  - python-venv
  - py-pip
  - py-cython
  - py-pybind11
  - py-torch@2.5.1 +custom-protobuf +distributed +fbgemm ~mkldnn +numpy +openmp +qnnpack ~rocm +numa +cudnn +magma +nccl ~gloo +mpi +onnx_ml +xnnpack +tensorpipe +caffe2 +kineto +valgrind  
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    default:
      link: all
      uenv:
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]

